version: '3.8'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../devops/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - VIRTUAL_ENV=/venv
      - PATH=/venv/bin:$PATH
  frontend:
    build:
      context: ../frontend
      dockerfile: ../devops/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app